---
title: "Plot of the Strategy Data"
# author: "Jerzy Pawlowski"
affiliation: MachineTrader.io
email: jpawlowski@machinetrader.io
# date: '`r format(Sys.time(), "%m-%d-%Y %H:%M")`'
output: html_document
runtime: shiny
---

```{r setup, include=FALSE, echo=TRUE}
# This is an R setup chunk, containing default options applied to all other chunks
knitr::opts_chunk$set(echo=FALSE)
library(rutils)
library(data.table)
library(dygraphs)
library(shiny)

# Download the PnLs array
# system("/Users/jerzy/Develop/shell/download_trade_tables3.sh")

# Get the strategy name
filen <- "/Users/jerzy/Develop/data/raw/StratRatchetPatModPairMSFT1SPY1pnl_20240807.csv"
stratn <- strsplit(filen, "/") %>% unlist %>% tail(1)
stratn <- strsplit(stratn, "_") %>% unlist
datev <- stratn[2]
datev <- strsplit(datev, "[.]") %>% unlist
datev <- datev[1]
stratn <- stratn[1]
# stratn <- strsplit(filen, "/") %>% unlist %>% tail(1) %>% strsplit("_") %>% unlist %>% head(1)
stratn <- substr(stratn, 6, nchar(stratn)-3)

# Load the PnLs array
dframe <- read.csv(filen)
dframe <- dframe[drop(dframe[, 1] > 0), ]
datev <- as.POSIXct(dframe[, 1]/1e3, origin="1970-01-01", tz="America/New_York")
pnls <- xts::xts(dframe[, -1], order.by=datev)
ncols <- NCOL(pnls)
pnls <- cbind(pnls, pnls[, ncols-1] + pnls[, ncols])
ncols <- NCOL(pnls)
colnames(pnls)[ncols] <- "totalPnL"
colv <- colnames(pnls)

```

```{r blah, include=FALSE}
print("This *Rmarkdown* document plots a *dygraph* plot of the PnLs array.")


```



```{r shiny, echo=FALSE}
shiny::fluidPage(
shiny::fluidRow(
  # Input the column 1 name
  column(width=2, shiny::selectInput("col1", label="Column 1:", choices=colv, selected=colv[1])),
  # Input the column 2 name
  column(width=2, shiny::selectInput("col2", label="Column 2:", choices=colv, selected=colv[2])),
),  # end fluidRow

  # Create output plot panel
  dygraphs::dygraphOutput("dyplot", width="90%", height="500px")

)  # end fluidPage interface

  # Calculate the data
  datav <- shiny::reactive({
    cat("Calculating the data\n")
    series1 <- get(input$col1, pnls)
    series2 <- get(input$col2, pnls)
    datav <- cbind(series1, series2)
    colnamev <- c(input$col1, input$col2)
    colnames(datav) <- colnamev
    datav
  })  # end reactive code
  

output$dyplot <- dygraphs::renderDygraph({
  datav <- datav()
  colnamev <- colnames(datav)
  # Plot the dygraph
  captiont <- paste("Strategy:", stratn, "/ Data for", colnamev[1], "and", colnamev[2])
  
  if (colnamev[2] == "pricEMA") {
  dygraphs::dygraph(datav, main=captiont) %>%
      dyOptions(colors=c("blue", "red"))
  } else {
  dygraphs::dygraph(datav, main=captiont) %>%
      dyAxis("y", label=colnamev[1], independentTicks=TRUE) %>%
      dyAxis("y2", label=colnamev[2], independentTicks=TRUE) %>%
      dySeries(name=colnamev[1], axis="y", strokeWidth=1, col="blue") %>%
      dySeries(name=colnamev[2], axis="y2", strokeWidth=1, col="red")
  } # end if
  
  # dygraphs::dygraph(get(input$col1, pnls), width="80%", height="600px")
})  # end renderDygraph
```

