% !Rnw weave = knitr
\documentclass{beamer}
\usepackage[latin1]{inputenc}
\usetheme{Warsaw}
\begin{document}

\title[FRE6811 Financial Software Laboratory]{A Minimal Demo of knitr\\Hope this works}
\author{Jerzy Pawlowski}
\institute{NYU Polytechnic Institute}
\date{\today}
\maketitle

<<setup, include=FALSE, cache=FALSE>>=
library(knitr)
# set global chunk options
opts_chunk$set(comment=NA, fig.width=6, fig.height=6)
@

\begin{frame}[fragile]
\frametitle{First sample slide}
This is a simple \textbf{knitr} demo with Brownian motion:

<<Brownian_motion, eval=TRUE, dev='png'>>=
set.seed(1213)  # for reproducibility
v.random = cumsum(rnorm(100))
mean(v.random)  # mean of v.random
plot(v.random, type='l')  # Brownian motion
@

Chart doesn't fit on page !

\end{frame}

\begin{frame}
\frametitle{Second sample slide}
A displayed formula:
\[
\int_{-\infty}^\infty e^{-x^2} \, dx = \sqrt{\pi}
\]
An itemized list:
\begin{itemize}
\item itemized item 1
\item itemized item 2
\item itemized item 3
\end{itemize}
\begin{theorem}
In a right triangle, the square of hypotenuse equals
the sum of squares of two other sides.
\end{theorem}
\end{frame}

\begin{frame}
\frametitle{Some Useful R Links}

Google Style Guide for R:
http://google-styleguide.googlecode.com/svn/trunk/Rguide.xml

\end{frame}

\end{document}
