\documentclass{beamer}
\usepackage[latin1]{inputenc}
\usetheme{Warsaw}
\begin{document}

<<setup, include=FALSE, cache=FALSE>>=
library(knitr)
# set global chunk options
opts_chunk$set(comment=NA, fig.width=6, fig.height=6)
@

\title[NewportLabs]{A Minimal Demo of knitr\\Hope this works}
\author{Jerzy Pawlowski}
\institute{NYU Polytechnic Institute}
\date{\today}
\maketitle

\begin{frame}[fragile]
This is a simple \textbf{knitr} demo with Brownian motion:

<<Brownian_motion, eval=TRUE, dev='png'>>=
set.seed(1213)  # for reproducibility
x = cumsum(rnorm(100))
mean(x)  # mean of x
plot(x, type='l')  # Brownian motion
@

Doesn't fit on page !

\end{frame}

\begin{frame}{A sample slide}
A displayed formula:
\[
\int_{-\infty}^\infty e^{-x^2} \, dx = \sqrt{\pi}
\]
An itemized list:
\begin{itemize}
\item itemized item 1
\item itemized item 2
\item itemized item 3
\end{itemize}
\begin{theorem}
In a right triangle, the square of hypotenuse equals
the sum of squares of two other sides.
\end{theorem}
\end{frame}


\end{document}
