---
title: "Identifying Biased Coin From Among Unbiased Coins"
author: "Jerzy Pawlowski"
affiliation: NYU Tandon School of Engineering
date: '`r format(Sys.time(), "%m/%d/%Y")`'
email: jp3900@nyu.edu
output: html_document
---

### How Many Coin Flips Are Needed to Distinguish a Biased Coin From Among Unbiased Coins?

We're given a set of coins, all of them unbiased except for one, which is biased. The biased coin has a probability of heads greater than 50% (say 60%).  We want to find the biased coin, so we flip the coins simultaneously $n$ times, and select the coin that produces the most heads.  If several coins produce the same number of heads, then we select from them a coin randomly.  

Calculate the probability of correctly selecting the biased coin, as a function of the number of coin flips, and the number of coins.

```{r eval=TRUE, echo=TRUE, fig.width=6, fig.height=4}
# Calculate the probability of selecting the biased coin, as a function of the number of coin flips, and the number of coins.
confi_dence <- function(num_flips, num_coins, p1, p2=0.5) {
  # calculate binomial probabilities for biased coin, using normal approximation for the binomial coefficient.
  if (p1^num_flips > 1e-10)
    binom_1 <- choose(num_flips, 0:num_flips) * p1^(0:num_flips) * (1-p1)^(num_flips:0)
  else
    binom_1 <- dnorm(0:num_flips, mean=num_flips*p1, sd=sqrt(num_flips*p1*(1-p1)))
  # calculate binomial probabilities for unbiased coins, using normal approximation for the binomial coefficient.
  if (p2^num_flips > 1e-10)
    binom_2 <- choose(num_flips, 0:num_flips) * p2^(0:num_flips) * (1-p2)^(num_flips:0)
  else
    binom_2 <- dnorm(0:num_flips, mean=num_flips*p2, sd=sqrt(num_flips*p2*(1-p2)))
  # probability of unbiased coin producing less than a certain number of heads
  cum_binom_2 <- cumsum(binom_2)
  cum_binom_2 <- c(0, cum_binom_2[-NROW(cum_binom_2)])
# probability of selecting the biased coin, when there's a tie in number of heads
  prob_tie <- sapply(binom_2, function(pro_b)
    sum(choose(num_coins-1, 1:(num_coins-1)) * pro_b^(1:(num_coins-1)) * (1-pro_b)^((num_coins-2):0) / (2:num_coins)))
# total probability of selecting the biased coin, including ties in number of heads
  sum(binom_1 * (cum_binom_2^(num_coins-1) + prob_tie))
}  # end confi_dence

# Probability of selecting the biased coin out of 2 coins, after 132 coin flips
confi_dence(132, num_coins=2, 0.6, 0.5)

# Probabilities of selecting the biased coin, as a function of the number of coin flips
num_flips <- 10:150
prob_s <- sapply(num_flips, confi_dence, p1=0.6, num_coins=2)

# Number of coin flips needed to select the biased coin, with 95% confidence
min_num_flips <- num_flips[findInterval(0.95, prob_s)]
min_num_flips


# Plot probabilities as a function of the number of coin flips
# Load plotly
suppressMessages(suppressWarnings(library(plotly)))
# Create data frame
da_ta <- data.frame(num_flips=num_flips, probs=prob_s)
# Plot with plotly using pipes syntax
da_ta %>% 
  plot_ly(x=~num_flips, y=~probs, type="scatter", mode="lines + markers", name="probability") %>% 
  add_trace(x=range(num_flips), y=0.95, mode="lines", line=list(color="red"), name="95% confidence") %>% 
  add_trace(x=min_num_flips, y=range(prob_s), mode="lines", line=list(color="green"), name=paste(min_num_flips, "flips")) %>% 
  layout(title="Probability of selecting biased coin from two coins", 
         xaxis=list(title="number of coin flips"),
         yaxis=list(title="probability"),
         legend=list(x=0.1, y=0.1))


# Probabilities of selecting the biased coin, as a function of the number of coins
num_coins <- 2:50
prob_s <- sapply(num_coins, confi_dence, p1=0.6, num_flips=50)
# prob_s <- cbind(num_coins, prob_s)
# plot(prob_s, t="l", main="Probabilities of selecting the biased coin, as a function of the number of coins")

# Plot probabilities as a function of the number of coins
# Create data frame
da_ta <- data.frame(num_coins=num_coins, probs=prob_s)
# Plot with plotly using pipes syntax
da_ta %>% 
  plot_ly(x=~num_coins, y=~probs, type="scatter", mode="lines + markers", name="probability") %>% 
  layout(title="Probability of selecting biased coin, from a number of coins", 
         xaxis=list(title="number of coins"),
         yaxis=list(title="probability"),
         legend=list(x=0.1, y=0.1))

```

### Old stuff: How Many Coin Flips Are Needed to Decide if a Coin is Biased?

You're given a coin, but you don't know if it's biased or not, so you flip it many times to see if it produces more heads than tails.  You do know that the coin is either biased (with a 60% probability of heads), or that it's unbiased.  You also know that the probability of getting either a biased or an unbiased coin is 50-50.  

Assume that you flip the coin $n$ times, and that you obtain $k$ heads.  You decide if the coin is biased or not by comparing the two binomial probabilities of obtaining $k$ heads.  If the probability of obtaining $k$ heads is greater for the biased coin, then you decide that it's biased, otherwise you decide that it's not biased.  In each case there's a probability that you're making a mistake, purely by chance.  The sum of those two probabilities is the probability that you're making a mistake and selecting the wrong coin.  

The probability of selecting the wrong coin depends on the number of coin flips, and decreases with more coin flips.  The function $confi\_dence()$ calculates the probability of selecting the biased coin, as a function of the number of coin flips.  

