---
title: Nonparametric Estimators as Machine Learning Features
author: Jerzy Pawlowski, NYU Tandon School of Engineering
date: June 5, 2020
output: pdf_document
---

## Abstract  

The large standard errors in the estimation of mean asset returns and their correlations produce large errors in portfolio optimization and machine learning models.  This is exacerbated by the large fat tails (leptokurtosis) of asset returns, especially for the highly leptokurtic high frequency returns.  For highly leptokurtic distributions, nonparametric estimators have lower standard errors than traditional moment estimators.  For example, the sample median has a smaller standard error than the sample mean.  But the median estimator is biased for skewed distributions.  We are thus faced with the bias-variance tradeoff. 

We introduce nonparametric estimators of the location, dispersion, and skewness, by expressing them as weighted sums of the median and higher quantiles of asset returns.  This is analogous to the Cornish–Fisher expansion.  The weights are chosen to reduce the estimator bias while still maintaining low variance, to achieve the best bias-variance tradeoff.  

We apply the nonparametric estimators to portfolio optimization and demonstrate better out-of-sample performance.  We implement the cross-validation simulations using an R package written in RcppArmadillo.


