<SCRIPT SRC='https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML'></SCRIPT>
<SCRIPT>MathJax.Hub.Config({ tex2jax: {inlineMath: [['$','$'], ['\\(','\\)']]}})</SCRIPT>

---
title: "Identifying Investment Managers Who Possess Skill"
author: "Jerzy Pawlowski"
affiliation: NYU Tandon School of Engineering
date: '`r format(Sys.time(), "%m/%d/%Y")`'
email: jp3900@nyu.edu
output: html_document
---

### Is it possible to identify managers who possess skill, based on their past returns?

Can we identify the best manager, who possesses the most skill in producing returns in excess of others, by selecting the one with the best past returns?  What is the probability of selecting the best manager, when we select the manager with the best past returns?  

The binomial coin flipping model can be adapted for identifying the best manager.  
Imagine two managers, one with skill, and the other without skill.
The daily returns of both managers are binary: either positive $+1$ or negative $-1$.
The returns of the manager without skill are random, with zero mean.
The returns of the skilled manager are also random, but with a positive drift, so that she produces a positive daily return more often than a negative return.
If the probability of a positive return is equal to $p > 0.5$, then the average daily return is equal to $(2*p-1)$, and the daily standard deviation is equal to $1$.
The annual return is equal to $250*(2*p-1)$, while the annual standard deviation is equal to $\sqrt{250}$, and the annual Sharpe ratio is equal to $\sqrt{250}*(2p-1)$.


```{r eval=TRUE, echo=TRUE, fig.width=5.5, fig.height=3.5}
# Sharpe ratio as function of daily probability
# sharpe_ratio <- sqrt(250)*(2*pro_b-1)

# Daily probability as function of Sharpe ratio
sharpe_ratio <- 0.4
pro_b <- (sharpe_ratio/sqrt(250)+1)/2

# Calculate probability of selecting skilled manager.
# Use normal approximation for the binomial coefficient.
confi_dence <- function(nu_m, p1, p2) {
  if (p1^nu_m > 1e-10)
    binom_1 <- choose(nu_m, 0:nu_m) * p1^(0:nu_m) * (1-p1)^(nu_m:0)
  else
    binom_1 <- dnorm(0:nu_m, mean=nu_m*p1, sd=sqrt(nu_m*p1*(1-p1)))
  if (p2^nu_m > 1e-10)
    binom_2 <- choose(nu_m, 0:nu_m) * p2^(0:nu_m) * (1-p2)^(nu_m:0)
  else
    binom_2 <- dnorm(0:nu_m, mean=nu_m*p2, sd=sqrt(nu_m*p2*(1-p2)))
  cum_binom_2 <- cumsum(binom_2)
  cum_binom_2 <- c(0, cum_binom_2[-NROW(cum_binom_2)])
  sum(binom_1 * (cum_binom_2 + binom_2/2))
}  # end confi_dence

# Probability of selecting skilled manager with 20 years of data
confi_dence(20*250, pro_b, 0.5)

# Annual probabilities of selecting skilled manager
year_s <- 1:50
prob_s <- sapply(250*year_s, confi_dence, p1=pro_b, p2=0.5)

# Years of data needed to select the skilled manager, with 95% confidence
num_years <- findInterval(0.95, prob_s)
num_years

# Load plotly
suppressMessages(suppressWarnings(library(plotly)))
# Create data frame
da_ta <- data.frame(years=year_s, probs=prob_s)
# Plot with plotly using pipes syntax
da_ta %>% 
  plot_ly(x=~years, y=~probs, type="scatter", mode="lines + markers", name="probability") %>% 
  add_trace(x=range(year_s), y=0.95, mode="lines", line=list(color="red"), name="95% confidence") %>% 
  add_trace(x=num_years, y=range(prob_s), mode="lines", line=list(color="green"), name=paste(num_years, "years")) %>% 
  layout(title="Probability of selecting skilled manager", 
         xaxis=list(title="years"),
         yaxis=list(title="probabilities"),
         legend=list(x=0.1, y=0.1))
```


