---
title: "Ornstein-Uhlenbeck process"
# author: "Jerzy Pawlowski"
affiliation: NYU Tandon School of Engineering
# date: '`r format(Sys.time(), "%m/%d/%Y")`'
email: jp3900@nyu.edu
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=TRUE)
# source("C:/Develop/R/scripts/ewma_model.R")
```

```{r ou_model, echo=FALSE}
inputPanel(
  sliderInput("vol_at", label="vol_at:",
              min=0.001, max=0.05, value=0.01, step=0.001),
  sliderInput("eq_price", label="eq_price:",
              min=1.0, max=10.0, value=5.0, step=0.1),
  sliderInput("the_ta", label="the_ta:",
              min=0.0001, max=0.05, value=0.005, step=0.0001)
)  # end inputPanel

renderPlot({
  
  vol_at <- input$vol_at
  eq_price <- input$eq_price
  the_ta <- input$the_ta
  
  # simulate Ornstein-Uhlenbeck process
  len_gth <- 1000
  re_turns <- numeric(len_gth)
  price_s <- numeric(len_gth)
  price_s[1] <- eq_price
  set.seed(1121)  # reset random numbers
  for (i in 2:len_gth) {
    re_turns[i] <- the_ta*(eq_price - price_s[i-1]) + 
      vol_at*rnorm(1)
    price_s[i] <- price_s[i-1] * exp(re_turns[i])
  }  # end for
  
  # plot
  plot(price_s, type="l", 
       xlab="periods", ylab="prices", 
       main="Ornstein-Uhlenbeck process")
  legend("topright", 
         title=paste(c(paste0("vol_at = ", vol_at), 
                       paste0("eq_price = ", eq_price),
                       paste0("the_ta = ", the_ta)),
                     collapse="\n"),
         legend="", cex=1.0, 
         inset=0.1, bg="white", bty="n")
  
})  # end renderPlot
```
