---
title: "Number of Coin Flips Needed to Identify Biased Coin"
author: "Jerzy Pawlowski"
affiliation: NYU Tandon School of Engineering
date: '`r format(Sys.time(), "%m/%d/%Y")`'
email: jp3900@nyu.edu
output: html_document
---

### How Many Coin Flips Are Needed to Decide if a Coin is Biased?

You're given a coin, but you don't know if it's biased or not, so you flip it many times to see if it produces more heads than tails.  You do know that the coin is either biased (with a 60% probability of heads), or that it's unbiased.  You also know that the probability of getting either a biased or an unbiased coin is 50-50.  

Assume that you flip the coin $n$ times, and that you obtain $k$ heads.  You decide if the coin is biased or not by comparing the two binomial probabilities of obtaining $k$ heads.  If the probability of obtaining $k$ heads is greater for the biased coin, then you decide that it's biased, otherwise you decide that it's not biased.  In each case there's a probability that you're making a mistake, purely by chance.  The sum of those two probabilities is the probability that you're making a mistake and selecting the wrong coin.  

The probability of selecting the wrong coin depends on the number of coin flips, and decreases with more coin flips.  The function $confi\_dence()$ calculates the probability of selecting the correct coin, as a function of the number of coin flips.  

```{r eval=TRUE, echo=TRUE, fig.width=6, fig.height=5}
# Calculate the probability of selecting the correct coin, as a function of the number of coin flips.
confi_dence <- function(nu_m, probv=0.6) {
  # use normal approximation for the binomial coefficients.
  bi_nom <- dnorm(0:nu_m, mean=nu_m*probv, sd=sqrt(nu_m*probv*(1-probv)))
  bi_nom_even <- dnorm(0:nu_m, mean=0.5*nu_m, sd=sqrt(0.25*nu_m))
  choos_e <- (bi_nom > bi_nom_even)
  1 - 0.5*(sum(bi_nom[!choos_e]) + sum(bi_nom_even[choos_e]))
}  # end confi_dence

# Calculate the probability of selecting the correct coin after 200 coin flips
confi_dence(200, probv=0.6)

# Calculate vector of probabilities of selecting the correct coin
num_flips <- 250:270
probs <- sapply(num_flips, confi_dence, probv=0.6)

# Calculate the number of coin flips needed to select the correct coin, with 95% confidence
min_num_flips <- num_flips[findInterval(0.95, probs)]
min_num_flips

# Plot vector of probabilities of selecting the correct coin
# Load plotly
suppressMessages(suppressWarnings(library(plotly)))
# Create data frame
datav <- data.frame(num_flips=num_flips, probs=probs)
# Plot with plotly using pipes syntax
datav %>% 
  plot_ly(x=~num_flips, y=~probs, type="scatter", mode="lines + markers", name="probability") %>% 
  add_trace(x=range(num_flips), y=0.95, mode="lines", line=list(color="red"), name="95% confidence") %>% 
  add_trace(x=min_num_flips, y=range(probs), mode="lines", line=list(color="green"), name=paste(min_num_flips, "coin flips")) %>% 
  layout(title="Number of Coin Flips Needed to Identify Biased Coin", 
         xaxis=list(title="coin flips"),
         yaxis=list(title="probabilities"),
         legend=list(x=0.1, y=0.1))
```


