---
title: "Identify turning points from SPY_predictor data"
author_no_print: "Jerzy Pawlowski"
affiliation: NYU Tandon School of Engineering
abstract: "Shiny app for trading rule: buy and hold for a fixed interval, and then revert to short, allows changing betas and plots cumulative PnL."
date_no_print: '`r format(Sys.time(), "%m/%d/%Y")`'
email: jp3900@nyu.edu
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=TRUE)
library(HighFreq)  # load package HighFreq
load("/Users/jerzy/Develop/data/SPY_predictor.RData")
returns_running <- 60*HighFreq::run_returns(xtes=HighFreq::SPY)
# colnames(returns_running) <- "returns"
# rangev <- match(index(SPY_predictor["2009-03-10/2009-03-13"]), index(SPY_predictor))
# source("/Users/jerzy/Develop/R/scripts/ewma_model.R")
```

```{r ewma_model, echo=FALSE}
inputPanel(
  sliderInput("returns", label="returns:",
              min=-2.0, max=5.0, value=2.0, step=0.01),
  sliderInput("variance", label="variance:",
              min=-2.0, max=2.0, value=0.0, step=0.01),
  sliderInput("ske_w", label="skew:",
              min=-2.0, max=2.0, value=0.0, step=0.01),
  sliderInput("hu_rst", label="hurst:",
              min=-2.0, max=2.0, value=2.0, step=0.01),
  sliderInput("interval", label="interval:",
              min=1.0, max=200.0, value=60, step=1.0)
)  # end inputPanel

renderPlot({

  returns <- input$returns
  variance <- input$variance
  ske_w <- input$ske_w
  hu_rst <- input$hu_rst
  interval <- input$interval

  betas <- c(returns, variance, ske_w, hu_rst)
  n_col <- NCOL(SPY_predictor)
  posv <- rep.int(NA, NROW(SPY_predictor))
  posv[1] <- 0
  # buy signal
  bu_y <- (SPY_predictor %*% betas[1:n_col] < -1)
  posv[bu_y] <- 1.0
  se_ll <- as.logical(rutils::lagit(bu_y, lag=interval))
  # sell signal
  posv[se_ll] <- -1.0
  posv[bu_y] <- 1.0
  posv <- zoo::na.locf(posv)
  # Lag the positions
  posv <- c(0, posv[-NROW(posv)])
  # pnls <- posv*returns
  # betav <- (sum(pnls * returns) - sum(pnls) * sum(returns)) / (sum(pnls * pnls) - sum(pnls)^2 )
  # -(exp(sum(pnls) - betav * sum(returns)) - 1)
  # -(exp(sum(posv*returns))-1) # / (sum(abs(rutils::diffit(posv))) / 2/ 1e5) / abs(sum(posv>0) - sum(posv<0))
  # pnls <- xts(exp(cumsum((posv * returns_running)))-1, order.by=index(SPY_predictor))
  chart_Series((exp(cumsum((posv * returns_running)))-1)[endpoints(SPY_predictor[, 1], on="days")], name="Backtest of static beta strategy for SPY")

  # plot(exp(cumsum((posv * returns_running)))-1, t="l", xlab="", ylab="")
  # chobj <- chart_Series(HighFreq::SPY[rangev, 4])
  # plot(chobj)
  # abline(v=which(bu_y[rangev] < -1), col="red", lwd=1)

})  # end renderPlot
```
